spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  secret-key: "testSecretKeyForJWTGeneration123!"
  access-token-expiration: 900000
  refresh-token-expiration: 86400000

logging:
  level:
    com.example.authservice: DEBUG